### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by JendaPlhak** [kushaldas/retask#13]
Hi, 
running following code:
```
import retask

q = retask.Queue("myQueue")
if q.connect():
    query = {
        'Hello': '42'
    }

    task = retask.Task(query)
    q.enqueue(task)

    task = q.wait()
```

causes following error on my system - 

```
Traceback (most recent call last):
  File "py/test.py", line 12, in <module>
    task = q.wait()
  File "/usr/local/lib/python3.4/dist-packages/retask/queue.py", line 159, in wait
    task.__dict__ = json.loads(data[1])
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I am running ubuntu 14.04. Retask installed using pip. Python version `3.4.3`. I was able to fix the error by substituting `json.loads(data[1])` to `json.loads(data[1].decode())` on lines https://github.com/kushaldas/retask/blob/master/retask/queue.py#L159 and https://github.com/kushaldas/retask/blob/master/retask/queue.py#L318 . 

Is that an error or am I doing wrong?

**Comment by kushaldas** [comment]
I am going to count this as an error.

**Comment by JendaPlhak** [comment]
Ok, should I open an pull request?

**Comment by chenxiaoqino** [comment]
I tried to fix it in PR #15 . @kushaldas

**Comment by abompard** [comment]
I'm hitting this issue too.
